services:
  # Serviço do Back-end
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_COOKIE_EXPIRES_IN: ${JWT_COOKIE_EXPIRES_IN}
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL}
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
