# docker-compose -f docker-compose.prod.yml up

services:
  # Serviço do Back-end
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.prod # Garante que usa o Dockerfile de produção
    ports:
      - "3000:3000" # Apenas a porta da API
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_COOKIE_EXPIRES_IN: ${JWT_COOKIE_EXPIRES_IN}
      MAILTRAP_TOKEN: ${MAILTRAP_TOKEN}
      MAILTRAP_INBOX_ID: ${MAILTRAP_INBOX_ID}
    restart: unless-stopped
    depends_on:
      - db

  # Serviço do Banco de Dados
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  postgres_data:
