# docker-compose -f docker-compose.prod.yml up

services:
  # Serviço do Back-end
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.prod # Garante que usa o Dockerfile de produção
    ports:
      - '3000:3000' # Apenas a porta da API
    restart: unless-stopped
    # As variáveis de ambiente serão fornecidas pelo seu servidor de produção,
    # ou pelo arquivo .env local ao usar este compose.
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_COOKIE_EXPIRES_IN: ${JWT_COOKIE_EXPIRES_IN}
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL}
    command: npm run start:prod:docker
    depends_on:
      - db

  # Serviço do Banco de Dados - AGORA COM MYSQL 5.6
  db:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      # A porta padrão do MySQL é 3306
      - '3306:3306'
    volumes:
      # O volume agora aponta para o diretório de dados do MySQL
      - mysql_data:/var/lib/mysql
    # Comando para garantir a codificação correta (UTF8)
    command:
      [--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]

volumes:
  # Nome do volume atualizado para clareza
  mysql_data:
