FROM node:22-alpine

RUN apk add --no-cache bash

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install -g nodemon

COPY . .

RUN npx prisma generate

RUN chmod +x ./scripts/init-db.sh

EXPOSE 3000

ENTRYPOINT ["./scripts/init-db.sh"]

CMD ["npm", "run", "start:dev:docker"]