# Use uma imagem oficial do Node.js
FROM node:22-alpine

# Instale dependências necessárias
RUN apk add --no-cache bash

# Defina o diretório de trabalho no contêiner
WORKDIR /usr/src/app

# Copie os arquivos de dependência
COPY package*.json ./

# Instale TODAS as dependências (incluindo devDependencies)
RUN npm install

# Instale nodemon globalmente para garantir que esteja disponível
RUN npm install -g nodemon

# Copie o restante dos arquivos da aplicação
COPY . .

# Gere o cliente Prisma
RUN npx prisma generate

# Torne o script executável
RUN chmod +x ./scripts/init-db.sh

# Exponha a porta que a aplicação usa
EXPOSE 3000

ENTRYPOINT ["./scripts/init-db.sh"]

CMD ["npm", "run", "start:dev:docker"]